services:
  #Node Container
  node:
    image: node:lts
    container_name: pizza-api-node
    tty: true
    user: "node:node"
    working_dir: /var/www
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/var/www
    networks:
      - app-network
    environment:
      HOST: 0.0.0.0

  #MySQL Container
  database:
    image: mariadb:10.3-bionic
    container_name: pizza-api-database
    tty: true
    ports:
      - "3306:3306"
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: pizza_api
      MYSQL_ROOT_PASSWORD: secret
    working_dir: /media
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network

  #PhpMyAdmin Container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pizza-api-phpmyadmin
    environment:
      PMA_HOST: pizza-api-database
      PMA_USER: root
      PMA_PASSWORD: secret
      MEMORY_LIMIT: 1024M
      UPLOAD_LIMIT: 1024M
    ports:
      - "8081:80"
    depends_on:
      - database
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local